# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path('./Resources/applicants_data.csv'))

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN', 'NAME'])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables = ['APPLICATION_TYPE', "AFFILIATION", 'CLASSIFICATION', "USE_CASE", "ORGANIZATION", "SPECIAL_CONSIDERATIONS"]

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [7]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [8]:
len(encoded_data[0])

105

In [9]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [11]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
    [applicant_data_df[["STATUS", "ASK_AMT", "IS_SUCCESSFUL"]], encoded_df],
    axis="columns",
    sort=False
)

# Review the Dataframe
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [12]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [13]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [14]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [15]:
X_train.dtypes

STATUS                         int64
ASK_AMT                        int64
APPLICATION_TYPE_T10         float64
APPLICATION_TYPE_T12         float64
APPLICATION_TYPE_T13         float64
                              ...
ORGANIZATION_Co-operative    float64
ORGANIZATION_Corporation     float64
ORGANIZATION_Trust           float64
SPECIAL_CONSIDERATIONS_N     float64
SPECIAL_CONSIDERATIONS_Y     float64
Length: 107, dtype: object

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [16]:
# Create a StandardScaler instance
X_scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [17]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[1])

# Review the number of features
number_input_features

107

In [18]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [19]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

54

In [20]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

27

In [21]:
# Create the Sequential model instance
nn = nn = Sequential()

In [22]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [23]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [24]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(1, activation="relu"))

In [25]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 54)                5832
_________________________________________________________________
dense_1 (Dense)              (None, 27)                1485
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 28
=================================================================
Total params: 7,345
Trainable params: 7,345
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [26]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [27]:
# Fit the model using 50 epochs and the training data
model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 657us/step - loss: 0.9466 - accuracy: 0.7016
Epoch 2/50
804/804 [==============================] - 1s 663us/step - loss: 1.1373 - accuracy: 0.6940
Epoch 3/50
804/804 [==============================] - 1s 723us/step - loss: 0.8253 - accuracy: 0.7227
Epoch 4/50
804/804 [==============================] - 1s 664us/step - loss: 0.8669 - accuracy: 0.72040s - loss: 0.8845 - accura
Epoch 5/50
804/804 [==============================] - 1s 677us/step - loss: 0.8250 - accuracy: 0.72400s - loss: 0.8581
Epoch 6/50
804/804 [==============================] - 1s 745us/step - loss: 0.8518 - accuracy: 0.7222
Epoch 7/50
804/804 [==============================] - 1s 681us/step - loss: 0.8622 - accuracy: 0.7205
Epoch 8/50
804/804 [==============================] - 1s 665us/step - loss: 0.8328 - accuracy: 0.7230
Epoch 9/50
804/804 [==============================] - 1s 656us/step - loss: 0.8679 - accuracy: 0.7158
Epoch 10/50
804/804 [==============================] - 1s 741us/step - loss: 0.8219 - accuracy: 0.7228
Epoch 11/50
804/804 [==============================] - 1s 646us/step - loss: 0.8532 - accuracy: 0.7210
Epoch 12/50
804/804 [==============================] - 1s 688us/step - loss: 0.8493 - accuracy: 0.7180
Epoch 13/50
804/804 [==============================] - 1s 767us/step - loss: 0.8461 - accuracy: 0.7215
Epoch 14/50
804/804 [==============================] - 1s 684us/step - loss: 0.7821 - accuracy: 0.7251
Epoch 15/50
804/804 [==============================] - 1s 773us/step - loss: 0.7812 - accuracy: 0.7202
Epoch 16/50
804/804 [==============================] - 1s 669us/step - loss: 0.7631 - accuracy: 0.7257
Epoch 17/50
804/804 [==============================] - 1s 658us/step - loss: 0.7461 - accuracy: 0.7273
Epoch 18/50
804/804 [==============================] - 1s 655us/step - loss: 0.7415 - accuracy: 0.7279
Epoch 19/50
804/804 [==============================] - 1s 711us/step - loss: 0.7390 - accuracy: 0.7283
Epoch 20/50
804/804 [==============================] - 1s 732us/step - loss: 0.7441 - accuracy: 0.7280
Epoch 21/50
804/804 [==============================] - 1s 796us/step - loss: 0.7576 - accuracy: 0.7215
Epoch 22/50
804/804 [==============================] - 1s 715us/step - loss: 0.7836 - accuracy: 0.7234
Epoch 23/50
804/804 [==============================] - 1s 772us/step - loss: 0.7654 - accuracy: 0.7268
Epoch 24/50
804/804 [==============================] - 1s 667us/step - loss: 0.7793 - accuracy: 0.7265
Epoch 25/50
804/804 [==============================] - 1s 666us/step - loss: 0.7651 - accuracy: 0.7269
Epoch 26/50
804/804 [==============================] - 1s 646us/step - loss: 0.7280 - accuracy: 0.7286
Epoch 27/50
804/804 [==============================] - 1s 653us/step - loss: 0.7463 - accuracy: 0.7252
Epoch 28/50
804/804 [==============================] - 1s 734us/step - loss: 0.7603 - accuracy: 0.7264
Epoch 29/50
804/804 [==============================] - 1s 714us/step - loss: 0.7577 - accuracy: 0.7203
Epoch 30/50
804/804 [==============================] - 1s 702us/step - loss: 0.7220 - accuracy: 0.7279
Epoch 31/50
804/804 [==============================] - 1s 682us/step - loss: 0.7183 - accuracy: 0.7292
Epoch 32/50
804/804 [==============================] - 1s 644us/step - loss: 0.7182 - accuracy: 0.7298
Epoch 33/50
804/804 [==============================] - 1s 650us/step - loss: 0.7172 - accuracy: 0.7304
Epoch 34/50
804/804 [==============================] - 1s 642us/step - loss: 0.7590 - accuracy: 0.7248
Epoch 35/50
804/804 [==============================] - 1s 647us/step - loss: 0.8138 - accuracy: 0.7258
Epoch 36/50
804/804 [==============================] - 1s 723us/step - loss: 0.8161 - accuracy: 0.7255
Epoch 37/50
804/804 [==============================] - 1s 661us/step - loss: 0.7390 - accuracy: 0.7281
Epoch 38/50
804/804 [==============================] - 1s 697us/step - loss: 0.7375 - accuracy: 0.7245
Epoch 39/50
804/804 [==============================] - 1s 658us/step - loss: 0.7519 - accuracy: 0.7265
Epoch 40/50
804/804 [==============================] - 1s 648us/step - loss: 0.7240 - accuracy: 0.7289
Epoch 41/50
804/804 [==============================] - 1s 648us/step - loss: 0.7177 - accuracy: 0.7293
Epoch 42/50
804/804 [==============================] - 1s 647us/step - loss: 0.7172 - accuracy: 0.7306
Epoch 43/50
804/804 [==============================] - 1s 649us/step - loss: 0.7607 - accuracy: 0.7226
Epoch 44/50
804/804 [==============================] - 1s 729us/step - loss: 0.7399 - accuracy: 0.7261
Epoch 45/50
804/804 [==============================] - 1s 673us/step - loss: 0.7437 - accuracy: 0.7255
Epoch 46/50
804/804 [==============================] - 1s 692us/step - loss: 0.7129 - accuracy: 0.7292
Epoch 47/50
804/804 [==============================] - 1s 699us/step - loss: 0.7173 - accuracy: 0.7300
Epoch 48/50
804/804 [==============================] - 1s 687us/step - loss: 0.7479 - accuracy: 0.7290
Epoch 49/50
804/804 [==============================] - 1s 657us/step - loss: 0.7600 - accuracy: 0.7262
Epoch 50/50
804/804 [==============================] - 1s 673us/step - loss: 0.7394 - accuracy: 0.7284

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [28]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.7230 - accuracy: 0.7258
Loss: 0.7229704856872559, Accuracy: 0.7258309125900269

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [29]:
# Set the model's file path
file_path = Path("../Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [30]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

107

In [31]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [32]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 =(number_input_features + 7) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

57

In [33]:
# Second hidden layer
hidden_nodes_layer2 = 19

In [50]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [51]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="sigmoid"))

# Second hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Output layer
nn_A1.add(Dense(1, activation="sigmoid"))

# Check the structure of the model
nn_A1.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_11 (Dense)             (None, 54)                5832
_________________________________________________________________
dense_12 (Dense)             (None, 19)                1045
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 20
=================================================================
Total params: 6,897
Trainable params: 6,897
Non-trainable params: 0
_________________________________________________________________

In [52]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=75)

Epoch 1/75
804/804 [==============================] - 1s 648us/step - loss: 0.6020 - accuracy: 0.7058
Epoch 2/75
804/804 [==============================] - 1s 653us/step - loss: 0.5780 - accuracy: 0.7203
Epoch 3/75
804/804 [==============================] - 1s 639us/step - loss: 0.5728 - accuracy: 0.7234
Epoch 4/75
804/804 [==============================] - 1s 666us/step - loss: 0.5670 - accuracy: 0.7238
Epoch 5/75
804/804 [==============================] - 1s 651us/step - loss: 0.5628 - accuracy: 0.7244
Epoch 6/75
804/804 [==============================] - 1s 635us/step - loss: 0.5599 - accuracy: 0.7258
Epoch 7/75
804/804 [==============================] - 1s 650us/step - loss: 0.5581 - accuracy: 0.7267
Epoch 8/75
804/804 [==============================] - 1s 663us/step - loss: 0.5568 - accuracy: 0.7271
Epoch 9/75
804/804 [==============================] - 1s 731us/step - loss: 0.5562 - accuracy: 0.7267
Epoch 10/75
804/804 [==============================] - 1s 752us/step - loss: 0.5557 - accuracy: 0.72700s - loss: 0.5557 - accuracy: 0.72
Epoch 11/75
804/804 [==============================] - 1s 739us/step - loss: 0.5546 - accuracy: 0.7276
Epoch 12/75
804/804 [==============================] - 1s 640us/step - loss: 0.5544 - accuracy: 0.7277
Epoch 13/75
804/804 [==============================] - 1s 719us/step - loss: 0.5537 - accuracy: 0.7283
Epoch 14/75
804/804 [==============================] - 1s 730us/step - loss: 0.5534 - accuracy: 0.7280
Epoch 15/75
804/804 [==============================] - 1s 640us/step - loss: 0.5527 - accuracy: 0.7288
Epoch 16/75
804/804 [==============================] - 1s 669us/step - loss: 0.5525 - accuracy: 0.7285
Epoch 17/75
804/804 [==============================] - 1s 691us/step - loss: 0.5523 - accuracy: 0.7274
Epoch 18/75
804/804 [==============================] - 1s 647us/step - loss: 0.5521 - accuracy: 0.7289
Epoch 19/75
804/804 [==============================] - 1s 633us/step - loss: 0.5517 - accuracy: 0.7287
Epoch 20/75
804/804 [==============================] - 1s 661us/step - loss: 0.5517 - accuracy: 0.7293
Epoch 21/75
804/804 [==============================] - 1s 786us/step - loss: 0.5515 - accuracy: 0.7280
Epoch 22/75
804/804 [==============================] - 1s 707us/step - loss: 0.5512 - accuracy: 0.7293
Epoch 23/75
804/804 [==============================] - 1s 632us/step - loss: 0.5507 - accuracy: 0.7287
Epoch 24/75
804/804 [==============================] - 1s 733us/step - loss: 0.5507 - accuracy: 0.7283
Epoch 25/75
804/804 [==============================] - 1s 648us/step - loss: 0.5504 - accuracy: 0.7285
Epoch 26/75
804/804 [==============================] - 1s 669us/step - loss: 0.5507 - accuracy: 0.7297
Epoch 27/75
804/804 [==============================] - 1s 671us/step - loss: 0.5501 - accuracy: 0.7282
Epoch 28/75
804/804 [==============================] - 1s 673us/step - loss: 0.5501 - accuracy: 0.7294
Epoch 29/75
804/804 [==============================] - 1s 661us/step - loss: 0.5496 - accuracy: 0.7294
Epoch 30/75
804/804 [==============================] - 1s 732us/step - loss: 0.5498 - accuracy: 0.7291
Epoch 31/75
804/804 [==============================] - 1s 722us/step - loss: 0.5493 - accuracy: 0.7293
Epoch 32/75
804/804 [==============================] - 1s 667us/step - loss: 0.5496 - accuracy: 0.7299
Epoch 33/75
804/804 [==============================] - 1s 656us/step - loss: 0.5494 - accuracy: 0.7303
Epoch 34/75
804/804 [==============================] - 1s 649us/step - loss: 0.5490 - accuracy: 0.7282
Epoch 35/75
804/804 [==============================] - 1s 668us/step - loss: 0.5485 - accuracy: 0.7293
Epoch 36/75
804/804 [==============================] - 1s 683us/step - loss: 0.5489 - accuracy: 0.7301
Epoch 37/75
804/804 [==============================] - 1s 651us/step - loss: 0.5487 - accuracy: 0.7299
Epoch 38/75
804/804 [==============================] - 1s 660us/step - loss: 0.5486 - accuracy: 0.7303
Epoch 39/75
804/804 [==============================] - 1s 659us/step - loss: 0.5484 - accuracy: 0.7310
Epoch 40/75
804/804 [==============================] - 1s 651us/step - loss: 0.5482 - accuracy: 0.7308
Epoch 41/75
804/804 [==============================] - 1s 721us/step - loss: 0.5479 - accuracy: 0.7309
Epoch 42/75
804/804 [==============================] - 1s 655us/step - loss: 0.5484 - accuracy: 0.7306
Epoch 43/75
804/804 [==============================] - 1s 659us/step - loss: 0.5481 - accuracy: 0.73000s - loss: 0.5485 - accuracy: 0.
Epoch 44/75
804/804 [==============================] - 1s 667us/step - loss: 0.5480 - accuracy: 0.7311
Epoch 45/75
804/804 [==============================] - 1s 684us/step - loss: 0.5478 - accuracy: 0.7308
Epoch 46/75
804/804 [==============================] - 1s 674us/step - loss: 0.5475 - accuracy: 0.7315
Epoch 47/75
804/804 [==============================] - 1s 659us/step - loss: 0.5474 - accuracy: 0.73090s - loss: 0.5457 - accura
Epoch 48/75
804/804 [==============================] - 1s 654us/step - loss: 0.5471 - accuracy: 0.7321
Epoch 49/75
804/804 [==============================] - 1s 731us/step - loss: 0.5472 - accuracy: 0.7325
Epoch 50/75
804/804 [==============================] - 1s 691us/step - loss: 0.5473 - accuracy: 0.7314
Epoch 51/75
804/804 [==============================] - 1s 652us/step - loss: 0.5474 - accuracy: 0.7318
Epoch 52/75
804/804 [==============================] - 1s 648us/step - loss: 0.5472 - accuracy: 0.7315
Epoch 53/75
804/804 [==============================] - 1s 668us/step - loss: 0.5467 - accuracy: 0.7311
Epoch 54/75
804/804 [==============================] - 1s 738us/step - loss: 0.5468 - accuracy: 0.7313
Epoch 55/75
804/804 [==============================] - 1s 654us/step - loss: 0.5468 - accuracy: 0.7320
Epoch 56/75
804/804 [==============================] - 1s 692us/step - loss: 0.5465 - accuracy: 0.7320
Epoch 57/75
804/804 [==============================] - 1s 747us/step - loss: 0.5467 - accuracy: 0.7315
Epoch 58/75
804/804 [==============================] - 1s 778us/step - loss: 0.5465 - accuracy: 0.7323
Epoch 59/75
804/804 [==============================] - 1s 653us/step - loss: 0.5461 - accuracy: 0.7319
Epoch 60/75
804/804 [==============================] - 1s 730us/step - loss: 0.5460 - accuracy: 0.7323
Epoch 61/75
804/804 [==============================] - 1s 709us/step - loss: 0.5461 - accuracy: 0.7319
Epoch 62/75
804/804 [==============================] - 1s 704us/step - loss: 0.5458 - accuracy: 0.7315
Epoch 63/75
804/804 [==============================] - 1s 716us/step - loss: 0.5459 - accuracy: 0.7318
Epoch 64/75
804/804 [==============================] - 1s 730us/step - loss: 0.5458 - accuracy: 0.7322
Epoch 65/75
804/804 [==============================] - 1s 773us/step - loss: 0.5457 - accuracy: 0.7321
Epoch 66/75
804/804 [==============================] - 1s 785us/step - loss: 0.5457 - accuracy: 0.7322
Epoch 67/75
804/804 [==============================] - 1s 742us/step - loss: 0.5456 - accuracy: 0.7319
Epoch 68/75
804/804 [==============================] - 1s 721us/step - loss: 0.5453 - accuracy: 0.7327
Epoch 69/75
804/804 [==============================] - 1s 674us/step - loss: 0.5454 - accuracy: 0.7323
Epoch 70/75
804/804 [==============================] - 1s 681us/step - loss: 0.5456 - accuracy: 0.7323
Epoch 71/75
804/804 [==============================] - 1s 810us/step - loss: 0.5454 - accuracy: 0.7328
Epoch 72/75
804/804 [==============================] - 1s 755us/step - loss: 0.5451 - accuracy: 0.7329
Epoch 73/75
804/804 [==============================] - 1s 718us/step - loss: 0.5451 - accuracy: 0.7327
Epoch 74/75
804/804 [==============================] - 1s 726us/step - loss: 0.5450 - accuracy: 0.7320
Epoch 75/75
804/804 [==============================] - 1s 701us/step - loss: 0.5451 - accuracy: 0.7325

#### Alternative Model 2

In [38]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

107

In [39]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [40]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = hidden_nodes_layer1_A2 = (number_input_features + number_output_neurons_A2) / 2.25

# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2= 24

# Define the number of hidden nodes for the third hidden layer
hidden_nodes_layer3_A2= 12

# Define the number of hidden nodes for the fourth hidden layer
hidden_nodes_layer4_A2= 6

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

48.0

In [41]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [42]:
# First hidden layer
nn_A2.add(Dense(input_dim= number_input_features, units= hidden_nodes_layer1_A2, activation="relu"))

#Second hidden layer

nn_A2.add(Dense( units= hidden_nodes_layer2_A2, activation="relu"))

# Third hidden layer
nn_A2.add(Dense( units= hidden_nodes_layer3_A2, activation="relu"))

# Fourth hidden layer
nn_A2.add(Dense( units= hidden_nodes_layer4_A2, activation="relu"))
# Output layer
nn_A2.add(Dense( 1, activation="linear"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 48)                5184
_________________________________________________________________
dense_7 (Dense)              (None, 24)                1176
_________________________________________________________________
dense_8 (Dense)              (None, 12)                300
_________________________________________________________________
dense_9 (Dense)              (None, 6)                 78
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 7
=================================================================
Total params: 6,745
Trainable params: 6,745
Non-trainable params: 0
_________________________________________________________________

In [43]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [44]:
# Fit the model
nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 798us/step - loss: 0.9212 - accuracy: 0.6050
Epoch 2/50
804/804 [==============================] - 1s 864us/step - loss: 0.7293 - accuracy: 0.7130
Epoch 3/50
804/804 [==============================] - 1s 726us/step - loss: 0.7131 - accuracy: 0.7189
Epoch 4/50
804/804 [==============================] - 1s 798us/step - loss: 0.7051 - accuracy: 0.71950s - loss: 0
Epoch 5/50
804/804 [==============================] - 1s 842us/step - loss: 0.7186 - accuracy: 0.7196
Epoch 6/50
804/804 [==============================] - 1s 791us/step - loss: 0.7514 - accuracy: 0.6943
Epoch 7/50
804/804 [==============================] - 1s 771us/step - loss: 0.6822 - accuracy: 0.7119
Epoch 8/50
804/804 [==============================] - 1s 811us/step - loss: 0.6638 - accuracy: 0.7231
Epoch 9/50
804/804 [==============================] - 1s 791us/step - loss: 0.6621 - accuracy: 0.7231
Epoch 10/50
804/804 [==============================] - 1s 788us/step - loss: 0.7334 - accuracy: 0.7175
Epoch 11/50
804/804 [==============================] - 1s 771us/step - loss: 0.7555 - accuracy: 0.7152
Epoch 12/50
804/804 [==============================] - 1s 780us/step - loss: 0.6903 - accuracy: 0.7203
Epoch 13/50
804/804 [==============================] - 1s 734us/step - loss: 0.6580 - accuracy: 0.7167
Epoch 14/50
804/804 [==============================] - 1s 731us/step - loss: 0.6579 - accuracy: 0.7222
Epoch 15/50
804/804 [==============================] - 1s 717us/step - loss: 0.6594 - accuracy: 0.7152
Epoch 16/50
804/804 [==============================] - 1s 701us/step - loss: 0.6362 - accuracy: 0.7255
Epoch 17/50
804/804 [==============================] - 1s 714us/step - loss: 0.6455 - accuracy: 0.7230
Epoch 18/50
804/804 [==============================] - 1s 714us/step - loss: 0.6429 - accuracy: 0.7189
Epoch 19/50
804/804 [==============================] - 1s 711us/step - loss: 0.6437 - accuracy: 0.7274
Epoch 20/50
804/804 [==============================] - 1s 711us/step - loss: 0.6431 - accuracy: 0.7272
Epoch 21/50
804/804 [==============================] - 1s 755us/step - loss: 0.6381 - accuracy: 0.7268
Epoch 22/50
804/804 [==============================] - 1s 786us/step - loss: 0.6423 - accuracy: 0.6988
Epoch 23/50
804/804 [==============================] - 1s 732us/step - loss: 0.6144 - accuracy: 0.72330s - loss: 0.6
Epoch 24/50
804/804 [==============================] - 1s 719us/step - loss: 0.6095 - accuracy: 0.7176
Epoch 25/50
804/804 [==============================] - 1s 721us/step - loss: 0.6024 - accuracy: 0.72660s - loss: 0.6024 - accuracy: 0.72
Epoch 26/50
804/804 [==============================] - 1s 796us/step - loss: 0.6385 - accuracy: 0.7266
Epoch 27/50
804/804 [==============================] - 1s 813us/step - loss: 0.6092 - accuracy: 0.7207
Epoch 28/50
804/804 [==============================] - 1s 736us/step - loss: 0.6005 - accuracy: 0.7262
Epoch 29/50
804/804 [==============================] - 1s 741us/step - loss: 0.5953 - accuracy: 0.7275
Epoch 30/50
804/804 [==============================] - 1s 752us/step - loss: 0.6029 - accuracy: 0.7282
Epoch 31/50
804/804 [==============================] - 1s 697us/step - loss: 0.6100 - accuracy: 0.7296
Epoch 32/50
804/804 [==============================] - 1s 721us/step - loss: 0.6371 - accuracy: 0.7204
Epoch 33/50
804/804 [==============================] - 1s 717us/step - loss: 0.6553 - accuracy: 0.7199
Epoch 34/50
804/804 [==============================] - 1s 732us/step - loss: 0.6212 - accuracy: 0.7249
Epoch 35/50
804/804 [==============================] - 1s 745us/step - loss: 0.6105 - accuracy: 0.7289
Epoch 36/50
804/804 [==============================] - 1s 719us/step - loss: 0.6104 - accuracy: 0.7299
Epoch 37/50
804/804 [==============================] - 1s 738us/step - loss: 0.6174 - accuracy: 0.7200
Epoch 38/50
804/804 [==============================] - 1s 721us/step - loss: 0.6142 - accuracy: 0.7295
Epoch 39/50
804/804 [==============================] - 1s 713us/step - loss: 0.6061 - accuracy: 0.7311
Epoch 40/50
804/804 [==============================] - 1s 730us/step - loss: 0.6113 - accuracy: 0.7310
Epoch 41/50
804/804 [==============================] - 1s 738us/step - loss: 0.6138 - accuracy: 0.7230
Epoch 42/50
804/804 [==============================] - 1s 726us/step - loss: 0.5996 - accuracy: 0.7304
Epoch 43/50
804/804 [==============================] - 1s 740us/step - loss: 0.6042 - accuracy: 0.7284
Epoch 44/50
804/804 [==============================] - 1s 747us/step - loss: 0.6034 - accuracy: 0.7307
Epoch 45/50
804/804 [==============================] - 1s 743us/step - loss: 0.6007 - accuracy: 0.7309
Epoch 46/50
804/804 [==============================] - 1s 819us/step - loss: 0.6014 - accuracy: 0.7301
Epoch 47/50
804/804 [==============================] - 1s 858us/step - loss: 0.6116 - accuracy: 0.7306
Epoch 48/50
804/804 [==============================] - 1s 733us/step - loss: 0.6118 - accuracy: 0.7207
Epoch 49/50
804/804 [==============================] - 1s 717us/step - loss: 0.6010 - accuracy: 0.7296
Epoch 50/50
804/804 [==============================] - 1s 726us/step - loss: 0.5946 - accuracy: 0.73130s - loss: 0.5991 - accuracy

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [54]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5553 - accuracy: 0.7279
Loss: 0.5552763342857361, Accuracy: 0.7279300093650818

In [55]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5546 - accuracy: 0.7263
Loss: 0.5546067953109741, Accuracy: 0.7262973785400391

In [56]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5874 - accuracy: 0.7265
Loss: 0.5874309539794922, Accuracy: 0.7265306115150452

### Step 3: Save each of your alternative models as an HDF5 file.

In [57]:
# Set the file path for the first alternative model
file_path = Path("../Resources/AlphabetSoup_A1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [58]:
# Set the file path for the second alternative model
file_path = Path("../Resources/AlphabetSoup_A2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)